# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Ferguson
email: jamesferguson497@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Full Stack Developer specializing in Node.js, Angular and Docker. Quality through constant
  improvement is my motto and I thrive on all kinds of feedback.
keywords: web, developer, javascript, hire
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamesfer.me" # the base hostname & protocol for your site

exclude:
  - package.json
  - node_modules


# Collections
collections:
  milestones:
  references:
  highlights:
  educations:
  experiences:


# Build settings
markdown: kramdown
