# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Ferguson - Resume
email: jamesferguson497@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Senior Data Engineer with 5 years of experience. I love building high performance pipelines and
  APIs with Kafka and Elasticsearch and I have significant experience with Scala and Typescript.
keywords: data, engineer, kafka, elasticsearch
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jamesfer.me" # the base hostname & protocol for your site

exclude:
  - package.json
  - node_modules
  - auto


# Collections
collections:
  milestones:
  references:
  highlights:
  educations:
  experiences:


# Build settings
markdown: kramdown
